# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12

pipelines:
  default:
    - step:
        script:
          - echo "And in all, the creator, preserver, destroyer, revealer and concealer of all that is."
          - npm ci
          - npm run test
  branches:
    main:
      - step:
          name: test & build
          script:
            - echo "This script runs only on commit to the master branch."
            - npm ci
            - npm run test
      - step:
          name: npm publish
          deployment: npm publish
          script:
            - echo "Publish to NPM"
            - npm ci
            - npm run build
            - pipe: atlassian/npm-publish:0.2.3
              variables:
                NPM_TOKEN: "$NPM_TOKEN"
