# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11

pipelines:
  default:
    - step:
        script:
          - echo "And in all, the creator, preserver, destroyer, revealer and concealer of all that is."
          - npm install
          - npm run lint
          - npm run test
          - npm run build
  branches:
    master:
      - step:
          name: test & build
          script:
            - echo "This script runs only on commit to the master branch."
            - npm install
            - npm run lint
            - npm run test
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: npm publish
          deployment: npm publish
          script:
            - echo "Publish to NPM"
            - pipe: atlassian/npm-publish:0.2.3
              variables:
                NPM_TOKEN: "$NPM_TOKEN"
                FOLDER: "dist"
          # activates jsdelivr as well I think
