# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6

pipelines:
  default:
    - step:
        script:
          - echo "And in all, the creator, preserver, destroyer, revealer and concealer of all that is."
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."
            # - git config --global user.email "gabrielmccallin@outlook.com"
            # - git config --global user.name "Gabriel McCallin"
            # - git push https://gabrielmccallin:itnujra010@github.com/gabrielmccallin/shiva.git
            # - npm publish activates jsdelivr as well I think
    publish: 
      - step:
          script:
            - echo "Publish"
            - npm install ci-publish