# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6

pipelines:
  default:
    - step:
        script:
          - echo "And in all, the creator, preserver, destroyer, revealer and concealer of all that is."
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."
            - npm install
            - npm run build
            - npm install ci-publish 
            - npm run ci-publish
            # activates jsdelivr as well I think            
    develop:
      - step:
          script:
            - npm install
            - npm run build